"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const verifyUser_1 = require("../middlewares/verifyUser");
const injection_1 = require("./injection");
const router = (0, express_1.Router)();
router.post("/createReply", verifyUser_1.verifyUser, injection_1.commentController.addReplyComment.bind(injection_1.commentController));
router.post("/:postId", verifyUser_1.verifyUser, injection_1.commentController.addComment.bind(injection_1.commentController));
router.patch("/:commentId", verifyUser_1.verifyUser, injection_1.commentController.editComment.bind(injection_1.commentController));
router.delete("/:commentId", verifyUser_1.verifyUser, injection_1.commentController.deleteComment.bind(injection_1.commentController));
exports.default = router;
