"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.postsServices = exports.userService = exports.reportsController = exports.adminController = exports.postController = exports.commentController = void 0;
const adminController_1 = __importDefault(require("../controllers/adminController"));
const commentsController_1 = __importDefault(require("../controllers/commentsController"));
const postController_1 = __importDefault(require("../controllers/postController"));
const reportsController_1 = __importDefault(require("../controllers/reportsController"));
const adminRepository_1 = __importDefault(require("../repositories/adminRepository"));
const userRepository_1 = __importDefault(require("../repositories/userRepository"));
const commentsRepository_1 = __importDefault(require("../repositories/commentsRepository"));
const postRepository_1 = __importDefault(require("../repositories/postRepository"));
const reportsRepository_1 = __importDefault(require("../repositories/reportsRepository"));
const userService_1 = __importDefault(require("../services/userService"));
const adminServices_1 = __importDefault(require("../services/adminServices"));
const commentsServices_1 = __importDefault(require("../services/commentsServices"));
const postService_1 = __importDefault(require("../services/postService"));
const reportsService_1 = __importDefault(require("../services/reportsService"));
const adminRepository = new adminRepository_1.default();
const userRepository = new userRepository_1.default();
const commentRepository = new commentsRepository_1.default();
const postRepository = new postRepository_1.default();
const reportsRepository = new reportsRepository_1.default();
const userService = new userService_1.default(userRepository);
exports.userService = userService;
const adminService = new adminServices_1.default(adminRepository);
const commentsServices = new commentsServices_1.default(commentRepository, postRepository);
const reportsService = new reportsService_1.default(reportsRepository);
const postsServices = new postService_1.default(postRepository);
exports.postsServices = postsServices;
const commentController = new commentsController_1.default(commentsServices, userService);
exports.commentController = commentController;
const adminController = new adminController_1.default(adminService);
exports.adminController = adminController;
const postController = new postController_1.default(postsServices, userService);
exports.postController = postController;
const reportsController = new reportsController_1.default(reportsService);
exports.reportsController = reportsController;
