name: dockerhub-frontend-service

on:
  push:
    branches: [ "main" ]
    paths: ["frontend/**"]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -  uses: actions/checkout@v4
      -  run: cd frontend && docker build --build-arg JWT_KEY=${{ secrets.JWT_KEY }} -t svignesh2409/socialconnect-frontend .
      -  run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
         env: 
             DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
             DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      -  run: docker push svignesh2409/socialconnect-frontend
