name: dockerhub-ads-service

on:
  push:
    branches: [ "main" ]
    paths: ["ads-service/**"]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v4
      -  run: cd ads-service && docker build -t svignesh2409/socialconnect-ads-service .
      -  run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
         env: 
             DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
             DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      -  run: docker push svignesh2409/socialconnect-ads-service
